name: flutter_maps
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^1.7.5
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^1.1.1
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true
